default_agent: domainanalyzer
agents:
  domainanalyzer:
    name: domainanalyzer
    entrypoint: app.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::309645991361:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-fa2629a6ea
      execution_role_auto_create: false
      account: '309645991361'
      region: us-east-1
      ecr_repository: 309645991361.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-domainanalyzer
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: domainanalyzer-CJTMTzFPN5
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:309645991361:runtime/domainanalyzer-CJTMTzFPN5
      agent_session_id: a5039233-dae4-47ef-a7f3-83153f35719d
    codebuild:
      project_name: bedrock-agentcore-domainanalyzer-builder
      execution_role: arn:aws:iam::309645991361:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-fa2629a6ea
      source_bucket: bedrock-agentcore-codebuild-sources-309645991361-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
