default_agent: app_content
agents:
  app_content:
    name: app_content
    entrypoint: app_content.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::309645991361:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-8d70e279fd
      execution_role_auto_create: false
      account: '309645991361'
      region: us-east-1
      ecr_repository: 309645991361.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-app_content
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: app_content-Js4Y56HdPw
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:309645991361:runtime/app_content-Js4Y56HdPw
      agent_session_id: 1e4bdd81-028d-47b9-8506-578add521109
    codebuild:
      project_name: bedrock-agentcore-app_content-builder
      execution_role: arn:aws:iam::309645991361:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-8d70e279fd
      source_bucket: bedrock-agentcore-codebuild-sources-309645991361-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
